/**
 * Inner Current (Внутренний ток)
 * Core Domain Types and Electrodynamic Circuit Models
 */

export const CircuitStatus = {
  SUPERCONDUCTING: 'SUPERCONDUCTING', // R -> 0, Mushin state (Flow, high efficiency)
  NOMINAL: 'NOMINAL',                 // Standard operation within acceptable parameters
  OHMIC_OVERHEAT: 'OHMIC_OVERHEAT',   // High R, Joule-Lenz thermal burn (Q = I^2 R t)
  EGO_SHORT_CIRCUIT: 'EGO_SHORT_CIRCUIT', // Ego loop short circuit: seeking validation from empty load
  REVERSE_POLARITY: 'EGO_SHORT_CIRCUIT', // Backward-compatible alias for Ego Short Circuit
  SHORT_CIRCUIT: 'SHORT_CIRCUIT',     // Load failure without Circuit Breaker isolation
  OPEN_CIRCUIT: 'OPEN_CIRCUIT'        // Disconnected load, stagnant core energy (apathy)
} as const;
export type CircuitStatus = typeof CircuitStatus[keyof typeof CircuitStatus];

export const BreakerStatus = {
  ARMED: 'ARMED',             // Zanshin active, monitoring circuit stability
  TRIPPED: 'TRIPPED',         // Load failed; breaker isolated core to prevent collapse
  RECOVERING: 'RECOVERING'    // Kintsugi recovery in progress
} as const;
export type BreakerStatus = typeof BreakerStatus[keyof typeof BreakerStatus];

export const LoadScale = {
  MICRO_TEA: 'MICRO_TEA',               // Simple sensory task (tea, breathing, single small action)
  FLOW_CODE: 'FLOW_CODE',               // Deep engineering, craft, writing, creative focus
  MACRO_ENTERPRISE: 'MACRO_ENTERPRISE'  // Business, high-stakes negotiations, empire building
} as const;
export type LoadScale = typeof LoadScale[keyof typeof LoadScale];

/**
 * 6 главных лампочек жизни (канонические потребители мощности цепи)
 */
export const CanonicalLoadDomain = {
  CAR: 'CAR',                         // Машина: мобильность, динамика, автономия перемещения
  HOME: 'HOME',                       // Дом: базовый контур, среда, крепость, очаг
  CAREER: 'CAREER',                   // Карьера: созидательное ремесло, влияние, масштаб
  RELATIONSHIPS: 'RELATIONSHIPS',     // Отношения: любовь, близость, семья, резонанс
  HEALTH: 'HEALTH',                   // Здоровье: физический скафандр, биохимия, витальность
  ENTERTAINMENT: 'ENTERTAINMENT'       // Развлечения: игра, дофамин, отдых, радость момента
} as const;
export type CanonicalLoadDomain = typeof CanonicalLoadDomain[keyof typeof CanonicalLoadDomain];


export interface TandenCore {
  /**
   * Autonomous Electromotive Force (EMF) generated by the core (0 - 100).
   * Does NOT depend on external recognition or feedback.
   */
  emf: number;

  /**
   * Stored core battery level (0 - 100)
   */
  reserve: number;

  /**
   * Center of gravity alignment (physical grounding / posture, 0 - 1)
   */
  grounding: number;
}

export interface ConductanceBus {
  /**
   * Base neural/mental resistance (0 - 100).
   * 0 = pure superconductivity.
   */
  baseResistance: number;

  /**
   * Parasitic inductance of past events (regret, guilt, resentment, 0 - 100)
   */
  parasiticPast: number;

  /**
   * Parasitic capacitance of future simulations (anxiety, catastrophe planning, 0 - 100)
   */
  parasiticFuture: number;

  /**
   * Noise level / inner critic chatter (0 - 1)
   */
  innerCriticNoise: number;
}

export interface LoadNode {
  id: string;
  name: string;
  scale: LoadScale;
  domain?: CanonicalLoadDomain;
  
  /**
   * Power requirement of the load (Watts nominal)
   */
  powerRequirement: number;

  /**
   * Fragility index of the external object (0 = antifragile, 1 = extremely fragile/mortal)
   */
  fragility: number;

  /**
   * Has the external load failed or broken? (e.g. project cancelled, investor rejected, cup broke)
   */
  isDamagedOrFailed: boolean;

  /**
   * Whether the user expects the load to feed validation/energy back (Ego short circuit trap)
   */
  expectationOfValidation: boolean;
}

export interface CircuitBreaker {
  status: BreakerStatus;
  
  /**
   * Zanshin factor: capacity to maintain mindful awareness after release/action (0 - 1)
   */
  zanshinAwareness: number;

  /**
   * Trip threshold (maximum allowed reverse shock before automatic disconnection)
   */
  tripThreshold: number;
}

export interface CircuitTelemetry {
  timestamp: number;
  core: TandenCore;
  bus: ConductanceBus;
  load: LoadNode | null;
  breaker: CircuitBreaker;

  /**
   * Duration in minutes spent in this exact mental state (delta t)
   */
  durationMinutes: number;
}

export interface RemediationStep {
  order: number;
  title: string;
  description: string;
  protocolName: string;
}

export interface DiagnosticResult {
  status: CircuitStatus;
  severity: 'OPTIMAL' | 'WARNING' | 'CRITICAL';
  currentAmperes: number;         // Useful current to load (0 if disconnected or shorted onto ego loop)
  effectiveResistance: number;    // R_eff = base + past + future
  thermalDissipationJoules: number; // Q = I^2 * R * t
  superconductivityIndex: number; // 0 (frozen/burnt) to 1.0 (pure flow)
  code: string;
  headline: string;
  physicsAnalysis: string;
  remediationProtocols: RemediationStep[];
}

/**
 * Состояние отдельной лампочки на 6-канальном распределительном щите
 */
export interface BulbChannel {
  domain: CanonicalLoadDomain;
  name: string;
  icon: string;
  allocatedPower: number; // Выделенная мощность (0 - 100 Вт / у.е.)
  expectationOfValidation: boolean; // Паразитная петля Эго (ожидание подтверждения ценности)
}

/**
 * 6-канальный распределительный щит нагрузок человека
 */
export interface SixBulbPanel {
  bulbs: Record<CanonicalLoadDomain, BulbChannel>;
}

/**
 * Результат экспресс-анализа балансировки 6 лампочек
 */
export interface SixBulbAnalysis {
  totalDemandedPower: number;
  availablePower: number;
  isUndervoltage: boolean;        // Просадка сети (P_demanded > P_available)
  activeBulbsCount: number;       // Количество горящих ламп (нагрузка > 15 Вт)
  dominantDomain: CanonicalLoadDomain | null; // Канал с максимальным отбором мощности
  starvedDomains: CanonicalLoadDomain[];      // Полностью обесточенные каналы
  diagnostics: string[];
}

/**
 * 5 ключевых архетипов человеческой боли (типичные виды несчастья)
 */
export const HumanPainArchetype = {
  BURNOUT_OVERTHINKING: 'BURNOUT_OVERTHINKING',       // Голова кипит, выгорание, тревога о будущем и самоедство за прошлое
  IMPOSTOR_VALIDATION: 'IMPOSTOR_VALIDATION',         // Самозванец, страх критики, зависимость от оценок, ступор перед показом
  COLLAPSE_SHOCK: 'COLLAPSE_SHOCK',                   // Крах внешнего дела/отношений — земля ушла из-под ног, жизнь кончена
  APATHY_STAGNATION: 'APATHY_STAGNATION',             // Хроническая лень, апатия, нет сил встать, всё бессмысленно (I = 0)
  OVERLOAD_HEALTH_DRAIN: 'OVERLOAD_HEALTH_DRAIN'      // Разрываюсь между делами, здоровье посыпалось, сеть просела
} as const;
export type HumanPainArchetype = typeof HumanPainArchetype[keyof typeof HumanPainArchetype];

export interface HumanPainDefinition {
  id: HumanPainArchetype;
  humanSymptom: string;      // Живая фраза человека («Голова взрывается, куча мыслей...»)
  humanCry: string;          // Субъективное переживание боли
  electrodynamicCause: {
    faultCode: string;
    headline: string;
    physicsLaw: string;      // Закон Джоуля — Ленца, закон полярности, закон сохранения масштаба
    affectedNode: string;    // Шина внимания, узел нагрузки, входной размыкатель, ключ коммутации
    parameterState: string;  // R >> 0, I < 0, Breaker tripped, I = 0, P_demanded > P_available
    explanation: string;     // Доступное физико-инженерное объяснение причины
  };
  remediationSolution: {
    protocolName: string;
    actionHeadline: string;
    immediateAction: string; // Что сделать прямо в эту секунду
    steps: RemediationStep[];
  };
}

/**
 * 23 онтологических канона Дзен и их взаимно-однозначные (биективные) физические соответствия
 */
export const ZenOntologyCanon = {
  // Уровень 1: Источник (Генератор)
  TANDEN: 'TANDEN',             // 丹田: Автономный реактор ЭДС (E)
  BUSSHO: 'BUSSHO',             // 仏性: Природа Будды = Номинал установленной мощности (P_rated)
  SHUNYATA: 'SHUNYATA',         // 空: Пустота / Шуньята = Волновой вакуум и нулевой импеданс (Z_0)

  // Уровень 2: Проводимость (Среда и Состояние)
  MUSHIN: 'MUSHIN',             // 無心: Не-ум = Сверхпроводимость шины внимания (R -> 0)
  FUDOSHIN: 'FUDOSHIN',         // 不動心: Непоколебимый дух = Стабилизатор рабочей точки (du/dt = 0)
  ZANSHIN: 'ZANSHIN',           // 残心: Остаточное осознание = Быстродействующий Circuit Breaker
  SHOSHIN: 'SHOSHIN',           // 初心: Ум новичка = Холодный сброс емкостей и индуктивностей (Reset)
  JIKISHININSHIN: 'JIKISHININSHIN', // 直指人心: Прямое указание = Прямая магистральная шина (Direct Bus)

  // Уровень 3: Аварии и Деградация (Потери цепи)
  JIGA: 'JIGA',                 // 自我: Эго = Шунтирование на себя и ток внутреннего КЗ (R_ego, I_кз = E / r_int)
  MAKYO: 'MAKYO',               // 魔境: Иллюзии/галлюцинации = Реактивные помехи (L_past, C_future)
  DUKKHA: 'DUKKHA',             // 苦: Страдание = Джоулево тепловое рассеяние (Q = I^2 R t)
  BONNO: 'BONNO',               // 煩悩: Омрачения/страсти = Токи утечки диэлектрика (I_leakage)

  // Уровень 4: Ремедиация и Инженерная практика
  SATORI: 'SATORI',             // 悟り: Просветление = Фазовый переход в сверхпроводимость (R = 0)
  KOAN: 'KOAN',                 // 公案: Коан = Контроллер разрыва логических петель (Exception Trap)
  SAMU: 'SAMU',                 // 作務: Физический труд = Сенсомоторный калибровочный стенд
  ICHIGO_ICHIE: 'ICHIGO_ICHIE', // 一期一会: Один миг — одна встреча = Дискретный квант времени (t = now)
  NIJIRIGUCHI: 'NIJIRIGUCHI',   // 躙口: Низкий лаз чайного домика = Шунт эго перед нагрузкой

  // Уровень 5: Форма, Структура и Эстетика
  KANSO: 'KANSO',               // 簡素: Простота = Минимальная топология цепи (Бритва Оккама)
  WABI_SABI: 'WABI_SABI',       // 侘寂: Несовершенство = Толерантность к энтропии нагрузки
  KINTSUGI: 'KINTSUGI',         // 金継ぎ: Золотой шов = Диэлектрический ремонт места аварии
  SHIBUMI: 'SHIBUMI',           // 渋味: Сдержанное совершенство = Согласование импедансов (Z_src = Z_load*)
  YUGEN: 'YUGEN',               // 幽玄: Неуловимая глубина = Внешнее магнитное поле проводника (B)
  FUKINZOKU: 'FUKINZOKU'        // 不均斉: Асимметрия = Динамический баланс Кирхгофа на 6 лампах
} as const;
export type ZenOntologyCanon = typeof ZenOntologyCanon[keyof typeof ZenOntologyCanon];


