/**
 * Inner Current (Внутренний ток)
 * Core Domain Types and Electrodynamic Circuit Models
 */

export const CircuitStatus = {
  SUPERCONDUCTING: 'SUPERCONDUCTING', // R -> 0, Mushin state (Flow, high efficiency)
  NOMINAL: 'NOMINAL',                 // Standard operation within acceptable parameters
  OHMIC_OVERHEAT: 'OHMIC_OVERHEAT',   // High R, Joule-Lenz thermal burn (Q = I^2 R t)
  REVERSE_POLARITY: 'REVERSE_POLARITY', // Reverse current: attempting to charge core from load
  SHORT_CIRCUIT: 'SHORT_CIRCUIT',     // Load failure without Circuit Breaker isolation
  OPEN_CIRCUIT: 'OPEN_CIRCUIT'        // Disconnected load, stagnant core energy (apathy)
} as const;
export type CircuitStatus = typeof CircuitStatus[keyof typeof CircuitStatus];

export const BreakerStatus = {
  ARMED: 'ARMED',             // Zanshin active, monitoring circuit stability
  TRIPPED: 'TRIPPED',         // Load failed; breaker isolated core to prevent collapse
  RECOVERING: 'RECOVERING'    // Kintsugi recovery in progress
} as const;
export type BreakerStatus = typeof BreakerStatus[keyof typeof BreakerStatus];

export const LoadScale = {
  MICRO_TEA: 'MICRO_TEA',               // Simple sensory task (tea, breathing, single small action)
  FLOW_CODE: 'FLOW_CODE',               // Deep engineering, craft, writing, creative focus
  MACRO_ENTERPRISE: 'MACRO_ENTERPRISE'  // Business, high-stakes negotiations, empire building
} as const;
export type LoadScale = typeof LoadScale[keyof typeof LoadScale];

/**
 * 6 главных лампочек жизни (канонические потребители мощности цепи)
 */
export const CanonicalLoadDomain = {
  CAR: 'CAR',                         // Машина: мобильность, динамика, автономия перемещения
  HOME: 'HOME',                       // Дом: базовый контур, среда, крепость, очаг
  CAREER: 'CAREER',                   // Карьера: созидательное ремесло, влияние, масштаб
  RELATIONSHIPS: 'RELATIONSHIPS',     // Отношения: любовь, близость, семья, резонанс
  HEALTH: 'HEALTH',                   // Здоровье: физический скафандр, биохимия, витальность
  ENTERTAINMENT: 'ENTERTAINMENT'       // Развлечения: игра, дофамин, отдых, радость момента
} as const;
export type CanonicalLoadDomain = typeof CanonicalLoadDomain[keyof typeof CanonicalLoadDomain];


export interface TandenCore {
  /**
   * Autonomous Electromotive Force (EMF) generated by the core (0 - 100).
   * Does NOT depend on external recognition or feedback.
   */
  emf: number;

  /**
   * Stored core battery level (0 - 100)
   */
  reserve: number;

  /**
   * Center of gravity alignment (physical grounding / posture, 0 - 1)
   */
  grounding: number;
}

export interface ConductanceBus {
  /**
   * Base neural/mental resistance (0 - 100).
   * 0 = pure superconductivity.
   */
  baseResistance: number;

  /**
   * Parasitic inductance of past events (regret, guilt, resentment, 0 - 100)
   */
  parasiticPast: number;

  /**
   * Parasitic capacitance of future simulations (anxiety, catastrophe planning, 0 - 100)
   */
  parasiticFuture: number;

  /**
   * Noise level / inner critic chatter (0 - 1)
   */
  innerCriticNoise: number;
}

export interface LoadNode {
  id: string;
  name: string;
  scale: LoadScale;
  domain?: CanonicalLoadDomain;
  
  /**
   * Power requirement of the load (Watts nominal)
   */
  powerRequirement: number;

  /**
   * Fragility index of the external object (0 = antifragile, 1 = extremely fragile/mortal)
   */
  fragility: number;

  /**
   * Has the external load failed or broken? (e.g. project cancelled, investor rejected, cup broke)
   */
  isDamagedOrFailed: boolean;

  /**
   * Whether the user expects the load to feed energy BACK to them (dangerous reverse expectation)
   */
  expectationOfValidation: boolean;
}

export interface CircuitBreaker {
  status: BreakerStatus;
  
  /**
   * Zanshin factor: capacity to maintain mindful awareness after release/action (0 - 1)
   */
  zanshinAwareness: number;

  /**
   * Trip threshold (maximum allowed reverse shock before automatic disconnection)
   */
  tripThreshold: number;
}

export interface CircuitTelemetry {
  timestamp: number;
  core: TandenCore;
  bus: ConductanceBus;
  load: LoadNode | null;
  breaker: CircuitBreaker;

  /**
   * Duration in minutes spent in this exact mental state (delta t)
   */
  durationMinutes: number;
}

export interface RemediationStep {
  order: number;
  title: string;
  description: string;
  protocolName: string;
}

export interface DiagnosticResult {
  status: CircuitStatus;
  severity: 'OPTIMAL' | 'WARNING' | 'CRITICAL';
  currentAmperes: number;         // Signed current: positive = forward flow, negative = reverse
  effectiveResistance: number;    // R_eff = base + past + future
  thermalDissipationJoules: number; // Q = I^2 * R * t
  superconductivityIndex: number; // 0 (frozen/burnt) to 1.0 (pure flow)
  code: string;
  headline: string;
  physicsAnalysis: string;
  remediationProtocols: RemediationStep[];
}

/**
 * Состояние отдельной лампочки на 6-канальном распределительном щите
 */
export interface BulbChannel {
  domain: CanonicalLoadDomain;
  name: string;
  icon: string;
  allocatedPower: number; // Выделенная мощность (0 - 100 Вт / у.е.)
  expectationOfValidation: boolean; // Паразитное ожидание обратной подпитки
}

/**
 * 6-канальный распределительный щит нагрузок человека
 */
export interface SixBulbPanel {
  bulbs: Record<CanonicalLoadDomain, BulbChannel>;
}

/**
 * Результат экспресс-анализа балансировки 6 лампочек
 */
export interface SixBulbAnalysis {
  totalDemandedPower: number;
  availablePower: number;
  isUndervoltage: boolean;        // Просадка сети (P_demanded > P_available)
  activeBulbsCount: number;       // Количество горящих ламп (нагрузка > 15 Вт)
  dominantDomain: CanonicalLoadDomain | null; // Канал с максимальным отбором мощности
  starvedDomains: CanonicalLoadDomain[];      // Полностью обесточенные каналы
  diagnostics: string[];
}

